import { Container } from "react-bootstrap";
import "bootstrap/dist/css/bootstrap.min.css";
import "./../globals.css";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        style={{
          backgroundImage: 'url("/car_login.png")',
          backgroundSize: "cover",
          backgroundRepeat: "no-repeat",
          margin: 0,
        }}
      >
        <Container fluid className="max-width p-0">
          <div
            style={{
              width: "35%",
              height: "100vh",
              backgroundColor: "white",
              marginLeft: "auto",
              display: "flex",
              justifyContent: "center",
              alignItems: "center",
            }}
          >
            {children}
          </div>
        </Container>
      </body>
    </html>
  );
}
